import { ReactQueryClientProvider } from '@/components/react-query-provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from '../contexts/auth-context';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <AuthProvider>
            <div className="max-w-3xl mx-auto p-4">{children}</div>
            <ToastContainer />
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
